name: Tdlib Android
on: [workflow_dispatch]
jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Install Depends
        run: sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev ninja-build
      - name: Clone Repo telegram bot api
        run: |
          git clone https://github.com/bsggr78/tddroid.git
          cd tddroid
          git clone https://github.com/tdlib/td tdlib-src
          cd build-folder
          chmod +x build-all.sh
          ./build-all.sh
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: Tdlib Android
          token: ${{ secrets.TOKEN }}
          artifacts: 'tddroid/build-folder/build-arm64-v8a/libtdjsonandroid.so'
